---
title: "qualidade_fd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analise de qualidade dos dados extraidos da folha com os dados originais - fd



```{r echo=FALSE}
load(file = "../output/tudo.RData")
# numero de actos
print(paste0("Numero de actos anestesicos: ",NROW(fd)))
# nome das colunas
print(paste0("Numero de colunas: ",NCOL(fd)))
names(fd)

# numero de NAs por coluna
print("Numero de dados ausentes por coluna: ")
sapply(fd,function(x) sum(is.na(x)))


```


## patologia previa
```{r patologia_previa, echo=FALSE}
patologia_previa
```
## tipo_anestesia
```{r tipo_anestesia, echo=FALSE}
tipo_anestesia
```
## ALR
```{r ALR, echo=FALSE}
ALR
```
```{r echo=FALSE}
print("Especialidade")
table(fd$Especialidade)
print("Diagnóstico")
table(fd$Diagnóstico)

print("Admissao")
table(fd$Admissão)
print("Genero")
table(fd$Género)
print("Idade")
table(fd$Idade)
print("Combinada")
table(fd$`Combinada?`)
print("Via aérea")
table(fd$`Via aérea`)
print("Técnicas e monitorizaçao")
table(fd$`Técnicas e monitorização`)
print("Acidentes e complicaçoes")
table(fd$`Acidentes e complicações`)
print("Alergias")
table(fd$Alergias)
print("ASA")
table(fd$ASA)
```

### CIRURGIAS
```{r, echo=FALSE}
data.frame(cirurgia$hits,cirurgia_regex$classe[as.numeric(cirurgia$n_hits)]) -> aa
names(aa) <- c("conceito","classe")
table(aa$conceito)
table(aa$classe)

```

